.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BURN 1 "May 30, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
burn \- create iso image, burn it to a CD-R[W], catalog burned CD, compare
CD data with the files iso were made from.

.SH SYNOPSIS
\fBburn\fR
.RI\ [ options ]\ <label>\ <file>...

.SH DESCRIPTION
\fBburn\fR creates iso, burns and catalogs it using mkisofs(8), cdrecord(1) and
mkat(1) respectively.

Use \fB-n\fR option to see how much space your files take. \fB-s, -c\fR
options control burn speed and if the CD needs to be blanked (in case of
CD-RW) by passing a parameter to cdrecord. \fB-r\fR option allows to pass any 
option through to cdrecord (e.g. -dummy).

If you don't want to catalog your CDs with mkat(1), use \fB--skip\fR
option.

.SH OPTIONS
.TP
.B \-n
print estimated iso image size
.TP
.B \-s \fI<SPEED>\fR
add 'speed=SPEED' to cdrecord parameters
.TP
.B \-c
clean the CR-RW (add 'blank=fast' to cdrecord parameters)
.TP
.B \-o
overburn (add '-overburn -dao' to cdrecord parameters)
.TP
.B \-r \fI<CDREC_OPTS>\fR
pass parameters to cdrecord
.TP
.B \-\-noimg
don't create image, useful when you already have an image. Label and files 
need not be specified.
.TP
.B \-\-nocat
skip catalog
.TP
.B \-\-nocheck
skip afterburn check
.TP
.B \-\-yes
don't ask for user input, just burn it
.TP
.B \-\-simulate
print commands that would be executed, implies --debug
.TP
.B \-\-debug
so you want to know how it works?
.TP
.B \-h, \-\-help
Show summary of options.

.SH EXAMPLES
.TP
burn -n 'Fruits Basket 10-13' Fruits\\ Basket\\ \\(1[0-3]*
Find out how much space files would take
.TP
burn -s4 -c --skip 'Fruits Basket 10-13' Fruits\\ Basket\\ \\(1[0-3]*
Burn a CDRW with 4x max speed, blanking it since it already has data on it,
skip catalog since it's a CDRW, so new data will probably be written soon.
.TP
burn -r'-dummy' 'Fruits Basket 10-13' Fruits\\ Basket\\ \\(1[0-3]*
Burn a CD-R in dummy mode

.SH FILES
.TP
.B /etc/mkatrc, ~/.mkatrc
config files where $CD, $DRIVE, etc. are defined

.SH SEE ALSO
\fImkat(1), mkatrc(5)\fR

.SH AUTHOR
This manual page was written by Dmitry Maksyoma <ledestin@amur.ru>,
for the Debian project (but may be used by others).
