.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BURN 1 "Jun 22, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
burn \- create iso image, burn it to a CD/DVD, catalog burned media, compare
burned data with the files iso were made from.

.SH SYNOPSIS
\fBburn\fR
.RI "[ options ] <label> <file>..."

.SH DESCRIPTION
\fBburn\fR creates iso, burns and catalogs it using mkisofs(8),
cdrecord(1)/growisofs(1) and mkat(1) respectively.

Use \fB-n\fR option to see how much space your files take. \fB-s, -c\fR
options control burn speed and if the CD needs to be blanked (in case of
CD-RW) by passing a parameter to the burning program. \fB-r\fR option allows
to pass any option through to the burning program (e.g. -dummy for cdrecord).
To check if the files you are burning are in the mkat db, use \fB--dbcheck\fR option,
if some of them are, it will ask you if you still want to burn the CD.

By default, first an image file will be created (takes some time), and then,
after the image is ready, the file is passed as an argument to a burning
program. It's also possible to burn image while it's being created by
piping image to a burning program. Use \fB-p, --pipe\fR option to
do that. It's faster to burn in that way, however, if somebody deletes files
you're about to burn, you will end up with a media without those files.

If you don't want to catalog your CDs with mkat(1), use \fB--nocat\fR
option.

.SH OPTIONS
.TP
.B \-n
print estimated iso image size
.TP
.B \-s \fI<SPEED>\fR
set burning speed
.TP
.B \-c
blank rewritable media
.TP
.B \-a, \-\-append
burn a multisession disk (cdrecord -multi, growisofs -M)
.TP
.B \-o
overburn
.TP
.B \-p, \-\-pipe
pipe image to a burning program as it's being created
.TP
.B \-r \fI<CDREC_OPTS>\fR
pass parameters to burning program
.TP
.B \-i \fI<MKIMG_OPTS>\fR
pass parameters to image making program
.TP
.B \-m \fI<MKAT_OPTS>\fR
pass parameters to mkat
.TP
.B \-\-media
specify media type (one of cd, dvd, bd, bd50). No default media type.
.TP
.B \-\-noimg
don't create image, useful when you already have an image. Label and files 
need not be specified.
.TP
.B \-\-nocat
skip catalog
.TP
.B \-\-nocheck
skip afterburn check
.TP
.B \-\-dbcheck
check if the files are already in mkat db (i.e. you have them burned
already)
.TP
.B \-y, \-\-yes
don't ask for user input, just burn it
.TP
.B \-\-simulate
print commands that would be executed, implies --debug
.TP
.B \-\-debug
so you want to know how it works?
.TP
.B \-h, \-\-help
Show summary of options.

.SH EXAMPLES
.TP
burn -n 'Fruits Basket 10-13' Fruits\\ Basket\\ \\(1[0-3]*
Find out how much space files would take
.TP
burn -s4 -c --nocat 'Fruits Basket 10-13' Fruits\\ Basket\\ \\(1[0-3]*
Burn a CDRW with 4x max speed, blanking it since it already has data on it,
skip catalog since it's a CDRW, so new data will probably be written soon.
.TP
burn -r'-dummy' 'Fruits Basket 10-13' Fruits\\ Basket\\ \\(1[0-3]*
Burn a CD-R in dummy mode

.SH FILES
.TP
.B /etc/mkatrc, ~/.mkatrc
config files where $CD, $DRIVE, etc. are defined

.SH SEE ALSO
\fImkat(1), mkatrc(5)\fR

.SH COPYRIGHT
Copyright 2004, 2005, 2007 Dmitry Maksyoma <ledestin@gmail.com>.
.br
Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
