.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MKAT 1 "May 30, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mkat \- catalog CDs and then search database by file name or md5 sum

.SH SYNOPSIS
\fBmkat\fR
.RI [ options ]

.SH DESCRIPTION
If called without options \fBmkat\fR tries to read files at $CD (see
\fImkatrc(5)\fR) and creates a .list file in $LISTDIR named after the CD label obtained
from the physical $DRIVE. Thus, it expects CD data to be available at $CD
and physical drive to be at $DRIVE.

A .list file contains CD label as first line, consecutive lines contain
CD directories and files. A file entry looks like this: 
\fBfilename:size:md5\fR.
Those files can be searched with a regexp using \fB-s\fR option.
Also, mkat can obtain a md5 sum of an existing file and grep for that 
sum (\fB-m\fR option).

\fBmkat\fR is automatically called from \fBburn\fR, but if you already 
have a lot of CDs, \fBmkat -y\fR will process a CD, eject it and wait 
for keyboard input (Enter), process next CD, and so on.

If a file with the same name as the CD label already exists in $LISTDIR,
\fB-f\fR option can be used to overwrite the file.

.SH OPTIONS
.TP
.B \-f
overwrite list file
.TP
.B \-m \fI<file>\fR
make md5 sum(s) and search for them in the db
.TP
.B \-s \fI<regex>\fR
search the CD database
.TP
.B \-y
cycle { mkat; eject; }
.TP
.B \-h, \-\-help
Show summary of options.

.SH EXAMPLES
.TP
mkat -s 'Fruits Basket 1.+'
Find files using grep regular expressions
.TP
mkat -m unknown_stuff.avi
Find out if the specified file exists in the catalog using its md5 sum

.SH FILES
.TP
.B /etc/mkatrc, ~/.mkatrc
config files where $CD, $DRIVE, etc. are defined

.SH SEE ALSO
\fIburn(1), mkatrc(5)\fR

.SH AUTHOR
This manual page was written by Dmitry Maksyoma <ledestin@amur.ru>,
for the Debian project (but may be used by others).
