.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MKATRC 1 "Apr 4, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mkatrc \- config file for MKAT tools

.SH SYNOPSIS
\fB/etc/mkatrc\fR
.P
\fB~/.mkatrc\fR

.SH DESCRIPTION
These files are sourced by MKAT programs, so, they are, naturally,
bash scripts. First \fI/etc/mkatrc\fR is sourced, then
\fI~/.mkatrc\fR, thus user-specific \fI.mkatrc\fR settings
override global settings from \fI/etc/mkatrc\fR.
Neither of config files is required, the variables could be, in principle,
defined in .bashrc.

The following variables must be set (mostly there will be sensible defaults in
/etc/mkatrc):
.TP
.B DRIVE
disc drive device (e.g. /dev/dvd)
.TP
.B CD
path where mounted disc files can be found (via autofs for example).
MKAT won't do any mounting.
.TP
.B LISTDIR
directory to store catalog (usually ~/.mkat)
.TP
.B ISO_IMAGE
path pointing at ISO image
.TP
.B TMP
directory for temporary files (grabbed wav files from newly burned audio CD to
compare with the files CD was burned from).
.TP
.B MKIMAGE_OPTS
arguments for image creation command
.TP
.B CD_BURN_CMD
command to burn a CD
.TP
.B DVD_BURN_CMD
command to burn a DVD/BD
.TP
.B MKIMAGE_CMD
command to create ISO image
.TP
.B AUTOFS_DELAY
sleep this amount of seconds before ejecting disc
.TP
.B MKAT_LIBPATH
path to the library needed for mkat commands

.SH SEE ALSO
\fIburn(1), mkat(1)\fR

.SH COPYRIGHT
Copyright 2004, 2005, 2013 Dmitry Maksyoma <ledestin@gmail.com>.
.br
Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
