.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MKATRC 1 "May 30, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mkatrc \- config file for MKAT tools

.SH SYNOPSIS
\fB/etc/mkatrc\fR
.P
\fB~/.mkatrc\fR

.SH DESCRIPTION
These files are sourced by MKAT tools, so, they are, naturally,
sh/bash scripts. First \fI/etc/mkatrc\fR sourced and then
\fI~/.mkatrc\fR is sourced, so \fI.mkatrc\fR settings override global 
settings from \fI/etc/mkatrc\fR.
Neither of config files is required, the variables could be, in principle,
defined in .bashrc.

.nf
The following variables must be set:
DRIVE="/dev/sr0" #physical CD drive
CD="/misc/cd"	 #mounted CD drive (autofs mounted in my case)
LISTDIR="/home/ledestin/.stuff/mkat" #where to place catalog database
TMP=/home/ledestin #where to place temporary files, can be used, for example,
		   #to grab wav files from newly burned audio CD to compare
		   #with the files CD was burned from.
MKISO_OPTS='-J -file-mode 444 -graft-points' #parameters for an image creation
					     #program, mkisofs in this case
CDREC_OPTS='-v' #parameters for cdrecord

#options for control freaks
AUTOFS_DELAY=6		     #how long to 'sleep' before ejecting CD
#meed the image creation program
MKIMAGE_CMD='mkisofs $MKISO_OPTS -V "$LABEL" -o "$ISO_IMAGE" "${FILES[@]}"'
ISO_IMAGE="$TMP/cdimage.iso" #where to create iso image with mkisofs
MKAT_LIBPATH=/usr/share/mkat
.fi

.SH SEE ALSO
\fIburn(1), mkat(1)\fR

.SH AUTHOR
This manual page was written by Dmitry Maksyoma <ledestin@amur.ru>,
for the Debian project (but may be used by others).
