.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MKAT-AUDIO 1 "May 31, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mkata \- catalog audio CD, check if CD is already in the catalog

.SH SYNOPSIS
\fBmkata\fR
.RI [ options ]

.SH DESCRIPTION
\fBmkata\fR tries to obtain audio CD id using cd-discid(1), reports
if the CD is already in the collection, adds the id to 
$LISTDIR/audiocd.list unless \fB-c\fR (check only) option is specified.

.SH OPTIONS
.TP
.B \-c
check only, don't add the CD to the collection
.TP
.B \-h
Show summary of options.

.SH FILES
.TP
.B /etc/mkatrc, ~/.mkatrc
config files where $CD, $DRIVE, etc. are defined

.SH SEE ALSO
\fIburna(1), mkatrc(5)\fR

.SH AUTHOR
This manual page was written by Dmitry Maksyoma <ledestin@amur.ru>,
for the Debian project (but may be used by others).
