.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MKATRC 1 "Apr 3, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mkatrc \- config file for MKAT tools

.SH SYNOPSIS
\fB/etc/mkatrc\fR
.P
\fB~/.mkatrc\fR

.SH DESCRIPTION
These files are sourced by MKAT programs, so, they are, naturally,
bash scripts. First \fI/etc/mkatrc\fR is sourced, then
\fI~/.mkatrc\fR, thus user-specific \fI.mkatrc\fR settings
override global settings from \fI/etc/mkatrc\fR.
Neither of config files is required, the variables could be, in principle,
defined in .bashrc.
See a sample config file in /usr/[local/]share/doc/mkat/examples/.

.nf
The following variables must be set:
DRIVE="/dev/sr0" #physical CD drive
CD="/misc/cd"	 #mounted CD drive (autofs mounted in my case)
#where to place catalog database
LISTDIR="/home/ledestin/.mkat"
#where to place temporary files (image to burn,
#grabbed wav files from newly burned audio CD to compare
#with the files CD was burned from).
TMP=/home/ledestin
#parameters for image creation (genisoimage)
MKIMAGE_OPTS='-J -iso-level=3 -file-mode 444 -graft-points' 
CD_BURN_CMD='wodim -v $REC_OPTS "$ISO_IMAGE"'
DVD_BURN_CMD='growisofs $REC_OPTS "$DVD_DRIVE"="$ISO_IMAGE"'

#options for control freaks
AUTOFS_DELAY=6		     #how long to 'sleep' before ejecting CD
#meed the image creation program
MKIMAGE_CMD='genisoimage $MKIMAGE_OPTS -V "$LABEL" -o "$ISO_IMAGE" "${FILES[@]}"'
ISO_IMAGE="$TMP/cdimage.iso" #where to create iso image with genisoimage 
#path to the library needed for mkat programs (helpers.sh)
MKAT_LIBPATH=/usr/share/mkat
.fi

.SH SEE ALSO
\fIburn(1), mkat(1)\fR

.SH COPYRIGHT
Copyright 2004, 2005, 2013 Dmitry Maksyoma <ledestin@gmail.com>.
.br
Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
