#!/bin/bash

# This file is part of Mkat
#
# Copyright (C) 2004 Dmitry Maksyoma <ledestin at amur.ru>. All
# Rights Reserved.
#
# Mkat is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
# USA.

#1. Make iso
#2. Burn iso
#3. Add the burned CD to the catalog
#4. Compare files on the CD with the original files

RCFILE=mkatrc 
[ -f /etc/$RCFILE ] && source /etc/$RCFILE
[ -f ~/.$RCFILE ] && source ~/.$RCFILE

function usage {
  echo "usage: $0 [options] <label> <file>..."
  echo "  -n		    print estimated image size, exit"
  echo "  -sSPEED	    add 'speed=SPEED' to cdrecord parameters"
  echo "  -c		    add 'blank=fast' to cdrecord parameters"
  echo "  -rCDREC_OPTS	    pass parameters to cdrecord"
  echo "      --noimg	    don't create image, just burn"
  echo "      --nocat	    skip catalog"
  echo "      --nocheck	    skip afterburn check"
  echo "      --yes	    don't ask questions"
  echo "      --simulate    print only, --debug implied"
  echo "      --debug	    how stuff works"
  echo "  -h, --help	    print this help"
  exit $1
}

function debug {
  [ -z $DEBUG ] || echo "$1"
}

found=1
while [ $found ]; do
  case "$1" in
    "-h"|"--help") usage 0 ;;
    "-n") PRINT_ONLY=1 ;;
    "--noimg") SKIP_MKIMAGE=1 ;;
    "--nocat") SKIP_CATALOG=1 ;;
    "--nocheck") SKIP_CHECK=1 ;;
    "--yes") NO_QUESTIONS=1 ;;
    "--simulate") SIMULATE=1; DEBUG=1 ;;
    "--debug") DEBUG=1 ;;
    "-c") CDREC_OPTS="$CDREC_OPTS blank=fast" ;;
       *) unset found ;;
  esac
  [ "${1:0:2}" = "-r" ] && { CDREC_OPTS="$CDREC_OPTS ${1:2}"; found=1; }
  [ "${1:0:2}" = "-s" ] && { CDREC_OPTS="$CDREC_OPTS speed=${1:2}"; found=1; }
  [ $found ] && shift;
done

#label and files must be provided
if [ -z $SKIP_MKIMAGE ] && [ "$#" -lt 2 ]; then
  echo >&2 "not enough parameters"
  usage 1
fi

set -e
IFS='
'

#MAKE ISO IMAGE
if [ -z $SKIP_MKIMAGE ]; then
  #vars needed for $MKIMAGE_CMD
  LABEL="$1"; shift; FILES=("$@")
fi

if [ $PRINT_ONLY ]; then
  str=`mkisofs -print-size -graft-points "$FILES"`
  echo "$str"
  size=`echo $str | tail -1`
  echo $(($size*2048/1024**2))Mb
  exit
elif [ -z $SKIP_MKIMAGE ]; then
  echo "making ISO image"
  eval "debug \"$MKIMAGE_CMD\""
  if [ -z $SIMULATE ]; then
    [ -d "$TMP" ] || mkdir "$TMP"
    eval "$MKIMAGE_CMD"
  fi
fi

#BURN
if [ -z $NO_QUESTIONS ] && [ -z $SKIP_MKIMAGE ]; then
  read -p "Press Enter to proceed to burn or Control-C to abort"
fi
echo "BURN!"
unset IFS
cmd="cdrecord $CDREC_OPTS $ISO_IMAGE"; debug "$cmd"
[ -z $SIMULATE ] && $cmd
IFS='
'

#CATALOG
if [ ! $SKIP_CATALOG ] && [ $CD ]; then
  echo "Catalog..."
  [ -z $SIMULATE ] && mkat
fi

#AFTERBURN CHECK
if [ ! $SKIP_CHECK ] && [ $CD ]; then
  set +e
  echo "Afterburn check..."
  if [ -z $SIMULATE ]; then
    for f in $*; do
      cmp "$f" "$CD/`basename $f`"
    done
  fi
fi

[ -z $SIMULATE ] && sleep $AUTOFS_DELAY && eject
