#!/bin/bash

RCFILE=cdlistrc 
[ -f /etc/$RCFILE ] && source /etc/$RCFILE
[ -f ~/.$RCFILE ] && source ~/.$RCFILE

[ _$1 = _"-s" ] && { shift; SKIP_BURN=1; }
if [ $# -lt 1 ]; then
  echo >&2 "missing arguments"
  echo "usage: $0 [-s] <wav file>..."
  echo "  -s	skip burn, only compare a CD with wav files"
  echo "mission: white an audio CD, rip it back and compare with the original"
  exit 1
fi

set -e
echo "Burning audioCD..."
[ ! $SKIP_BURN ] && cdrecord -v -dao -speed=4 -audio "$@"

echo "Ripping the burned CD..."
TMP=`mktemp -p "$TMP" -d`; cd "$TMP"
trap "rm -rf $TMP" EXIT
cdparanoia -Bw
WRITTEN=(`ls -1`)

PARAMS=("$@"); i=0
cd ~-
set +e
echo "Comparing ripped files with the original..."
BROKEN_RECORD=0
while [ $# -gt $i ]; do
  cmp "${PARAMS[$i]}" "$TMP/${WRITTEN[$i]}"
  [ $? -eq 1 ] && BROKEN_RECORD=1
  i=$(($i+1))
done
if [ ! $BROKEN_RECORD ]; then
  echo "Catalog the CD..."
  cdlist-audio
fi
echo "Done..."
eject
