#!/bin/bash

# This file is part of Mkat
#
# Copyright (C) 2004 Dmitry Maksyoma <ledestin at amur.ru>. All
# Rights Reserved.
#
# Mkat is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
# USA.

RCFILE=mkatrc 
[ -f /etc/$RCFILE ] && source /etc/$RCFILE

function usage {
  echo "usage: $0 [option]";
  echo "  -f			overwrite list file"
  echo "  -p <path>		catalog path instead of a CD"
  echo "  -t <tag[,tag]...>     write list file with 'tags:' string"
  echo "  -s <regex>		search the catalog database"
  echo "  -nt			don't search tags with -s (no tags)"
  echo "  -to <tag[,tag]...>	search within tags only (tags only)"
  echo "  -m <file>...		make md5 sum(s) and search for them in the db"
  echo "      --md5dir <dir>	print files with md5 sums not present in the db"
  echo "  -y			cycle { mkat; eject; }"
  echo "  -q			be quiet"
  echo "  --rc <file>		read file instead of default (~/.$RCFILE)"
  echo "  -d, --debug		debug output"
  echo "  -h, --help		print this help"
  exit $1
}

function check_option {
  name=$1; val=$2
  if [ -z "$val" ]; then
    echo >&2 "$name option requires argument"
    usage 1
  fi
}

function debug {
  [ -z $DEBUG ] || echo "$@"
}

#process parameters
found=1
while [ $found ] && [ ${#*} -ne 0 ] ; do
  case "$1" in
    "-f") FORCE_OVERWRITE=1 ;;
    "-rc") CONFIG="$2"; check_option $*; shift ;;
    "-h"|"--help") usage 0 ;;
    "-d"|"--debug") DEBUG=1 ;;
    "-q") CHILD_PARAMS="-q"; GREP_PARAMS="-q" ;;
    "-y") CYCLE_CATALOG=1 ;;
    "-p") CATALOG_PATH=$2
          CATALOG_PATH=${CATALOG_PATH%%/}
          check_option $*; shift ;;
    "--md5dir")
      DIR="$2"
      [ -z "$DIR" ] && DIR=. ;;
    "-s") REGEX="$2"; check_option $*; shift ;;
    "-nt") FILTER_TAGS=1 ;;
    "-to") TAG_REGEX="$2"; TAG_REGEX="(${TAG_REGEX//,/|/})"
	   check_option $*; shift ;;
    "-t")
      TAGS="$2"; TAGS=${TAGS//,/ }
      check_option $*; shift ;;
    *) unset found ;;
  esac
  [ $found ] && shift
done

if [ -z $found ]; then
  echo >&2 "unknown options: $*"; usage 1
fi

#source rc file
#-rc specified config must exist
[ "$CONFIG" ] && \
  ([ -f "$CONFIG" ] || { echo >&2 "file not found: $CONFIG"; exit 1; })
CONFIG=${CONFIG:-~/.$RCFILE}
debug "reading rc file: $CONFIG"
[ -f $CONFIG ] && source $CONFIG

MKAT="$0${CHILD_PARAMS:+ $CHILD_PARAMS}"

#process --md5dir option
if [ "$DIR" ]; then
  IFS=:
  for f in `find "$DIR" -type f -printf '%p:'`; do
    $MKAT -q -m "$f"
    [ $? -ne 0 ] && echo "$f";
  done;
  exit
fi

#tag search (-to)
if [ "$TAG_REGEX" ]; then
  grep $GREP_PARAMS -i -E "^tags:.+$TAG_REGEX" "$LISTDIR"/*.list
  exit $?
fi

#search the database with grep (-s option)
if [ "$REGEX" ]; then
  IFS=''
  cmd="grep $GREP_PARAMS -i -E "$REGEX" "$LISTDIR"/*.list"
  [ $FILTER_TAGS ] && cmd="$cmd | grep -v -E '(^|:)tags:'"
  debug "$cmd"
  eval $cmd
  exit $?
fi

#search by md5 sum of a file
if [ "_$1" = "_-m" ]; then
  shift
  md5sum "$@" | awk '{ printf "%s|", $1 }' | sed 's/|$/\n/' | xargs $MKAT -s
  exit $?
fi

#catalog many CDs: cycle mkat, eject, wait for user input
if [ $CYCLE_CATALOG ]; then
  while : ; do
    $MKAT && sleep $AUTOFS_DELAY && eject
    read -p "Press Enter when ready..."
    [ $? -eq 0 ] || exit
  done
fi

#catalog the CD
if [ -z "$CATALOG_PATH" ]; then
  LABEL=`isoinfo -d -i $DRIVE | sed -ne 's/Volume id: //p'`
  [ -z "$LABEL" ] && { echo "could not obtain CD label"; LABEL="NO_LABEL"; }
else
  LABEL="$CATALOG_PATH"
fi

if [ "$CATALOG_PATH" ]; then
  FNAME=${CATALOG_PATH#/}
  FNAME=${FNAME//\//.}
  CD=$CATALOG_PATH
  TAGS="$TAGS filesystem"; TAGS=${TAGS# }
else
  FNAME=$LABEL
  TAGS="$TAGS cd"; TAGS=${TAGS# }
fi
DEST="$LISTDIR/$FNAME.list"
{ [ -z $FORCE_OVERWRITE ] \
  && [ -e "$DEST" ] ; } && \
  { echo >&2 "file already exists: '$DEST'"; exit 1; }

{
echo $LABEL
[ "$TAGS" ] && echo "tags: $TAGS"
IFS='
'
for f in `find $CD -mindepth 1`; do
  rel=`echo "$f" | sed -ne "s!${CD%%/}/!!p"`
  if [ -f "$f" ]; then
    echo -e $rel:`du -h "$f" | awk '{print $1}'`:`md5sum "$f" | awk '{ print $1}'`
  else
    echo $rel
  fi
done
} | tee "$DEST"
