#!/bin/bash

RCFILE=mkatrc 
[ -f /etc/$RCFILE ] && source /etc/$RCFILE
[ -f ~/.$RCFILE ] && source ~/.$RCFILE

function usage {
  echo "usage: $0 [option]";
  echo "  -f		 overwrite list file"
  echo "  -s <regex>	 search the CD database"
  echo "  -m <file>	 make md5 sum(s) and search for them in the db"
  echo "  -y		 cycle { mkat; eject; }"
  echo "  -h, --help     print this help"
  exit $1
}

case "$1" in
"-h"|"--help") usage 0 ;;
esac

[ _$1 = _"-s" ] && { grep -i -E "$2" "$LISTDIR"/*.list; exit; }
if [ _$1 = _"-y" ]; then
  while : ; do
    mkat && sleep $AUTOFS_DELAY && eject
    read -p "Press Enter when ready..."
    [ $? -eq 0 ] || exit
  done
fi
#search by md5 sum of a file
if [ _"$1" = _"-m" ]; then
  shift
  md5sum "$@" | awk '{ printf "%s|", $1 }' | sed 's/|$/\n/' | xargs $0 -s 
  exit
fi

#catalog the CD
LABEL=`isoinfo -d -i $DRIVE | sed -ne 's/Volume id: //p'`
[ -z "$LABEL" ] && { echo "could not obtain CD label"; exit 1; }
DEST="$LISTDIR/$LABEL.list"
{ [ _$1 != _"-f" ] \
  && [ -e "$DEST" ] ; } && \
  { echo >&2 "file already exists: '$DEST'"; exit 1; }

{
echo $LABEL
IFS='
'
for f in `find $CD -mindepth 1`; do
  rel=`echo "$f" | sed -ne "s!$CD!!;s!^/!!p"`
  if [ -d "$f" ]; then
    echo $rel
  elif [ -f "$f" ]; then
    echo -e $rel:`du -h "$f" | awk '{print $1}'`:`md5sum "$f" | awk '{ print $1}'`
  fi
done
} | tee "$DEST"
