#!/bin/bash

for DIR in $(find releases -type d); do
  (
    echo -e "<html>\n<body>\n<h1>Mkat releases</h1>\n<hr/>\n<pre>"
    find "$DIR" -type f -printf '%P\n' | grep -v "^index\.html$" \
        | awk "{ printf \"<a href=\\\"$DIR/%s\\\">%s</a>\n\",\$1,\$1 }"
    echo -e "</pre>\n</body>\n</html>"
  ) > index.html
done
